### ISSUE TITLE
Update 0.26.2 breaks sense2vec install

### ISSUE THREAD

**Issue by elyase** [spacy-io/murmurhash#7]
Not sure if this should be reported here, but this is the error message:

```
    building 'sense2vec.vectors' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/sense2vec
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/miniconda3/envs/industry-mapper/include/python2.7 -I/home/ubuntu/industry-mapper/sense2vec/include -I/home/ubuntu/miniconda3/envs/industry-mapper/include/python2.7 -I/home/ubuntu/miniconda3/envs/industry-mapper/lib/python2.7/site-packages/numpy/core/include -I/home/ubuntu/miniconda3/envs/industry-mapper/lib/python2.7/site-packages/murmurhash/headers -c sense2vec/vectors.cpp -o build/temp.linux-x86_64-2.7/sense2vec/vectors.o -O3 -Wno-unused-function -fno-stack-protector
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    sense2vec/vectors.cpp:258:36: fatal error: murmurhash/MurmurHash3.h: No such file or directory
     #include "murmurhash/MurmurHash3.h"
                                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by honnibal** [comment]
Just encountered this too.

The sense2vec install is currently occurring via the repository, which takes a different path from the regular package installation (as it builds the Cython files). I haven't worked out why this breaks the headers yet.

**Comment by honnibal** [comment]
@henningpeters , could this be caused by `zip_safe=True`?

I think we're pretty lax about using `pkg_resources` instead of `__file__` to access things, e.g. the header files.

**Comment by henningpeters** [comment]
Oh yes, that's very likely.

**Comment by henningpeters** [comment]
I hope I fixed the issue. While cleaning up some stuff in murmurhash I broke the header lookup. I also changed the code to use `pkg_resources` and did some basic tests with eggs. Would be great to get feedback whether it's not working for you.
