### ISSUE TITLE
Cannot install on Windows + Python 2.7, but can on 3.3, 3.4, and 3.5

### ISSUE THREAD

**Issue by suchow** [spacy-io/murmurhash#8]
I've created a minimal example of installing murmurhash using pip on AppVeyor here: https://github.com/suchow/test-murmurhash. It runs successfully on Windows and Python 3.3, 3.4, and 3.5, but not on 2.7.

The error it gives is:

```
murmurhash/mrmr.cpp(248) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

Here are the full build logs: https://ci.appveyor.com/project/suchow/test-murmurhash/build/1.0.1/job/r9t9duixfppuaefx#L13.

**Comment by henningpeters** [comment]
Microsoft forgot to include that header in VS Studio 2008, it's a common error that's not specific to murmurhash. Please obtain the header, e.g., from https://msinttypes.googlecode.com/svn/trunk/stdint.h and place it in an include directory (e.g., under <python-dir>/include).

**Comment by suchow** [comment]
Thank you, I can confirm that this fixed the issue.

**Comment by henningpeters** [comment]
Btw: we are now packaging stdint.h with murmurhash, so you don't need to download/install it yourself anymore.
