### ISSUE TITLE
how to use this lib

### ISSUE THREAD

**Issue by largetalk** [spacy-io/murmurhash#9]
hello, how to use this lib
In [1]: import mrmr

In [2]: dir(mrmr)
Out[2]: 
['__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__pyx_capi__',
 '__test__']

**Comment by henningpeters** [comment]
Sorry, this library doesn't ship with docs at the moment, please feel invited to contribute.

Also have a look at the function signatures in https://github.com/spacy-io/murmurhash/blob/master/murmurhash/mrmr.pyx which are more or less self-explanatory:

```
cdef uint32_t hash32(void* key, int length, uint32_t seed) nogil:
cdef uint64_t hash64(void* key, int length, uint64_t seed) nogil:
cdef uint64_t real_hash64(void* key, int length, uint64_t seed) nogil:
```

For usage examples please take a look at the spaCy repository, e.g., https://github.com/spacy-io/spaCy/blob/master/spacy/matcher.pyx#L0282
